#!/usr/bin/php
<?php
/**	(c) 2014 Everett Morse
 *	www.neptic.com
 *	
 *	Simple script to invoke the Lunch v1 importer
 */

//Load the same environment as the web app
define('ROOT_DIR',realpath(dirname(__FILE__) . '/..'));
include_once ROOT_DIR.'/config/config.php';
include_once ROOT_DIR.'/lib/engine/autoload.php';

if( count($argv) < 3 ) {
	echo "Usage: import <group id> <action>\n";
	echo "Use action 'help' for more info\n";
	exit;
}

$group = Group::find($argv[1]);
$imp = new OldLunchImporter($group, "old_lunch");
//$imp->listUsers();
$action = $argv[2];
if( count($argv) >= 3 )
	$imp->$action($argv[3]);
else
	$imp->$action();

?>
