#! /bin/bash
config=$1
if [ "$config" = "" ]; then
	config="local"
fi

toself=$(dirname $0)
root="$toself/../../.."
phpconfIn="$root/config/config.$config.php"
phpconfOut="$root/config/config.php"
jsconfIn="$root/config/config.$config.js"
jsconfOut="$root/config/config.js"

if [ ! -f "$jsconfIn" ]; then
	echo "Cannot find Node.js config file for $config"
	exit 1
fi

if [ ! -f "$phpconfIn" ]; then
	echo "Cannot find PHP config file for $config"
	exit 1
fi

echo "Swithcing to config: $config (this will overwrite anything in current config files)"
cp -f "$jsconfIn" "$jsconfOut"
cp -f "$phpconfIn" "$phpconfOut"

# Maybe have .htaccess file to use too
htaccessIn="$root/config/htaccess.$config.conf"
if [ -f "$htaccessIn" ]; then
	cp -f "$htaccessIn" "$root/.htaccess"
fi

