#!/usr/bin/php
<?php
/**	
 * @author Everett Morse
 * @copyright (c) 2014 Everett Morse
 * www.neptic.com
 *	
 * Setup project directory structure, including scripts dir with symlinks to engine's scripts.
 * Copies in various templates as a starting point.
 */


/**
 * Entry point.
 */
function main() {
	if( !isInProjectDir() ) {
		echo "You should create a project directory with the engine code located in lib/engine/" .
				PHP_EOL;
		exit(1);
	}
	
	createDirs();
	linkScripts();
	copyTemplates();
	installIndex();
	writeGitIgnore();
	
	echo "== Done ==" . PHP_EOL;
	
	echo PHP_EOL;
	echo "TODO: " . PHP_EOL;
	echo " - Read README." . PHP_EOL;
	echo " - Create project GIT/SVN repo." . PHP_EOL;
	echo " - Edit config/htaccess.example.php to point to your project directory." . PHP_EOL;
	echo " - Edit config/config.example.php (and rename)" . PHP_EOL;
	echo " - Run ./scripts/select_config example" . PHP_EOL;
	echo " - Build stuff!" . PHP_EOL;
	echo PHP_EOL;
}

function isInProjectDir() {
	return file_exists("lib/engine") && is_dir("lib/engine");
}

function createDirs() {
	mkdirLog("app");
	mkdirLog("app/api");
	mkdirLog("app/controllers");
	mkdirLog("app/migrations");
	mkdirLog("app/models");
	mkdirLog("app/views");
	mkdirLog("app/views/layouts");
	mkdirLog("cache");
	`chmod 666 cache` #this makes it much easier, but you should restrict to your web user.
	mkdirLog("config");
	mkdirLog("public");
	mkdirLog("scripts");
	mkdirLog("test");
	mkdirLog("work");
}

function mkdirLog($dir) {
	if( mkdir($dir) ) {
		echo "Created: $dir" . PHP_EOL;
	} else {
		echo "ERROR: failed to make directory \"{$dir}\"" . PHP_EOL;
		exit(1);
	}
}

function linkScripts() {
	echo "Linking scripts ..." . PHP_EOL;
	chdir("scripts");
	$scriptPath = "../lib/engine/scripts/";
	$scripts = scandir($scriptPath);
	foreach($scripts as $script) {
		if( !is_dir($scriptPath.$script) && is_executable($scriptPath.$script) ) {
			`ln -s "{$scriptPath}$script" "$script"`;
		}
	}
	chdir("..");
}

function installIndex() {
	echo "Installing index.php ..." . PHP_EOL;
	`cp lib/engine/index.php index.php`;
}

function copyTemplates() {
	$tplDir = "lib/engine/scripts/templates/setup/";
	copyTpls($tplDir,"./");
}

function copyTpls($from, $to) {
	echo "Copying templates to \"$to\"" . PHP_EOL;
	$tpls = scandir($from);
	foreach($tpls as $tpl) {
		if( substr($tpl,0,1) == "." ) continue; //skip invisibles, especially "." and ".."
		if( is_dir($from.$tpl) ) {
			if( is_dir($to.$tpl) || mkdir($to.$tpl) ) {
				copyTpls($from.$tpl.'/', $to.$tpl.'/');
			} else {
				echo "ERROR: Failed to make dir for templates at \"$to$tpl\"" . PHP_EOL;
			}
		} else {
			//echo "cp \"$from$tpl\" \"$to$tpl\"" . PHP_EOL;
			`cp "$from$tpl" "$to$tpl"`;
		}
	}
}

function writeGitIgnore() {
	$ignore = array(
		".DS_Store",
		"config.*.php",
		"config.*.js",
		"htaccess.*.conf",
		"config/config.php",
		"config/config.js",
		".htaccess",
		"cache",
		"work"
	);
	file_put_contents(".gitignore",implode(PHP_EOL, $ignore));
}


main();
?>